[smtp]
server = "smtp.gmail.com"
port = 587
use_ssl = true

[imap]
server = "imap.gmail.com"
port = 993

[credentials]
email = "youremail@gmail.com"
password = "your_password"
app_password = "apppass_madeinyourgmail"

[sender]
display_name = "yourname"
display_email = "youremail@gmail.com"
alternative_email = ""
